version: "3"

services:
  web:
    build: .
    ports:
    - ${PORT-8080}:8080
    environment:
    - PROFILE=postgres
    - SPRING_DATASOURCE_URL=jdbc:postgresql://db/music

  db:
    image: postgres:alpine
    environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
    - POSTGRES_DB=music

