apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: ghcr.io/jpetazzo/spring-music
        name: spring-music
        env:
        - name: PROFILE
          value: postgres
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://db/music
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            port: http
        resources:
          requests:
            cpu: 0.1
            memory: 250M
          limits:
            cpu: 2
            memory: 1G
